// Compose an agent's final system prompt = authoritative brand canon + the
// agent's own behavior spec. The canon block is generated by `npm run brand-pack`
// (from brand/brand-pack.yaml) into agents/_canon.json.
//
// Every place that pushes an agent version (setup*.ts, update.ts) runs its system.md
// through here, so identity/positioning/voice/proof/ICP live in ONE source and can
// never drift between the agents and the CRM.

import { readFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CANON = resolve(__dirname, "../agents/_canon.json");

export type Consumer = "dossier" | "radar" | "sponsor" | "outreach";

export function withCanon(consumer: Consumer, systemMd: string): string {
  if (!existsSync(CANON)) {
    throw new Error("Missing agents/_canon.json — run `npm run brand-pack` first.");
  }
  const pack = JSON.parse(readFileSync(CANON, "utf8"));
  const block: string | undefined = pack.blocks?.[consumer];
  if (!block) throw new Error(`No canon block for "${consumer}" in agents/_canon.json`);
  return `${block}\n\n${systemMd}`;
}

// Substitute {{VARS}} in a system prompt at push time. Identity comes from the
// compiled brand pack; delivery config from .env. Used by the digest (the only
// prompt that needs to know an email address or the CRM's public URL).
export function renderVars(systemMd: string): string {
  const pack = existsSync(CANON) ? JSON.parse(readFileSync(CANON, "utf8")) : {};
  const identity = pack.identity ?? {};
  const vars: Record<string, string | undefined> = {
    BRAND_NAME: identity.name,
    BRAND_ABBR: identity.abbr,
    FOUNDER: identity.founder,
    NEVER_USE: pack.never_use,
    CRM_URL: process.env.CRM_URL,
    DIGEST_TO: process.env.DIGEST_TO,
    EMAIL_FROM: process.env.EMAIL_FROM,
  };
  return systemMd.replace(/\{\{(\w+)\}\}/g, (_, k: string) => {
    const v = vars[k];
    if (!v) throw new Error(`Unresolved {{${k}}} — set it in .env (or the brand pack) before pushing this prompt.`);
    return v;
  });
}
